---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "add configMap"
  name: nodejs-demo
  labels:
    app: nodejs-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodejs-demo
  template:
    metadata:
      labels:
        app: nodejs-demo
    spec:
      containers:
      - name: nodejs-demo
        image: slldemoacr.azurecr.io/nodejs/demo:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: nodejs-demo