apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
StringData:
  DATABASE_NAME: $(DATABASE_NAME)
  DATABASE_USER: $(DATABASE_USER)
  DATABASE_PASSWORD: $(DATABASE_PASSWORD)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "add database secrets and specific key"
  name: nodejs-demo
  labels:
    app: nodejs-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodejs-demo
  template:
    metadata:
      labels:
        app: nodejs-demo
    spec:
      containers:
      - name: nodejs-demo
        image: slldemoacr.azurecr.io/nodejs/demo:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: NODE_ENV
          value: production
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_PASSWORD
        volumeMounts:
        - name: tls-certs
          mountPath: "/etc/tls"
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: my-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 8000
  selector:
    app: nodejs-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-demo-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - xelaexpeditionsrx.com
    secretName: my-tls-secret
  rules:
  - host: xelaexpeditionsrx.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-demo
            port:
              number: 8000